---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  vars:
    hostname: 192.168.29.195
    username: administrator@vsphere.local
    password: B@ond007
    cluster: LAB
    datacenter: LABDC
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: testvm_{{ item }}
      #name: testvm_3
      template: vm1
      datacenter: "{{ datacenter }}"
      folder: testvms
      state: poweredoff
      cluster: "{{ cluster}}"
      wait_for_ip_address: no
    delegate_to: localhost
    with_items:
     - 1
     - 2
     - 3
