---
- name: Role ensures that the socks tunnel is setup
  hosts: list_host
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel-nopassphrase

- hosts: " {{ list_host }}"
  gather_facts: no
  tasks:
    - shell: echo Hello `hostname`
      register: result
