---
- name: Role ensures that the socks tunnel is setup
  hosts: area51-controller
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel-nopassphrase

  tasks:
    - name: Gather fact for all vm
      vmware_vm_info:
        hostname: "{{ list_host }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
        #proxy_host: 192.168.29.186
        #proxy_port: 3128
        validate_certs: no
      register: vms
      delegate_to: localhost
