---
- name: Sock tunnel setup
  hosts: "{{ list_host }}"
  gather_facts: false

  tasks:
    - name: Gather fact for all vm
      vmware_vm_info:
        hostname: "{{ list_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        proxy_host: 192.168.29.172
        proxy_port: 8080
        validate_certs: no
      register: vms
      delegate_to: localhost
